import { createUserGoogleCalendarClient } from "../calendar/userGoogleCalendar";
import {
  AgentContentBlock,
  ToolExecutionResult,
} from "../agent/types";
import {
  AgentRuntimeRequest,
  agentRuntimeRequestSchema,
} from "./contracts";
import { CalendarDraftRepository } from "../repo/calendarDraftRepository";
import { ChannelMemoryRepository } from "../repo/channelMemoryRepository";
import { GoogleOAuthConnectionRepository } from "../repo/googleOAuthConnectionRepository";
import { MemoryItemRepository } from "../repo/memoryItemRepository";
import { RecurringTaskRepository } from "../repo/recurringTaskRepository";
import { TaskRepository } from "../repo/taskRepository";
import { TaskEventRepository } from "../repo/taskEventRepository";
import { TaskStateRepository } from "../repo/taskStateRepository";
import { EventBridgeScheduledReminderScheduler } from "../scheduler/scheduledReminder";
import { UserPreferenceRepository } from "../repo/userPreferenceRepository";
import { SecretsProvider } from "../aws/secretsProvider";
import { logger } from "../shared/logger";
import { CustomToolExecutor } from "../tools/executeCustomTool";
import { customToolDefinitions } from "../tools/definitions";
import { OpenMeteoWeatherProvider } from "../weather/openMeteo";
import { WebToolsProvider } from "../web/webTools";
import { DynamoDbSkillRepository } from "../skills/dynamoDbSkillRepository";
import { SkillRegistry, formatSkillSummariesForPrompt } from "../skills/registry";

type DynamicImport = <T = Record<string, unknown>>(specifier: string) => Promise<T>;
type SessionHistoryMessage = {
  role: "user" | "assistant";
  content: string;
};
const bedrockServiceTiers = ["reserved", "priority", "default", "flex"] as const;
type BedrockServiceTier = (typeof bedrockServiceTiers)[number];

const dynamicImport = new Function("specifier", "return import(specifier)") as DynamicImport;
const sessionHistories = new Map<string, SessionHistoryMessage[]>();
const maxSessionHistoryMessages = 20;
const defaultSystemPrompt = `You are a helpful assistant.
Answer in the user's language unless the user asks otherwise.
Use tools for durable memory, one-off tasks, recurring task definitions, and calendar operations when they are relevant.
Use skill management tools only for reusable workflows: propose a generated SKILL.md draft after the user agrees, and enable it only after explicit approval.
Use recurring task tools for daily, weekly, monthly, or otherwise repeated duties instead of creating a one-off task for the rule.
Use scheduled reminder tools when the user explicitly asks to create, list, edit, disable, or delete a separate recurring Slack notification generated by the assistant.
Distinguish scheduled reminders from recurring task definitions: scheduled reminders control when the assistant posts; recurring task definitions control duties included in summaries.
Do not proactively create or offer a separate scheduled reminder for one-off events; only create one when the user clearly asks for an individual reminder or a new notification schedule.
When the user wants an event, checklist, or note included in an existing daily reminder, store it as a task, recurring task, or memory item; do not create a separate scheduled reminder.
When you extract durable information from a user-supplied image, PDF, document, or attachment and the user did not explicitly ask to remember it, summarize it and ask whether to save it before calling save_memory.
If a previous turn created an individual scheduled reminder and the user says it is not needed or should be included in the daily reminder instead, delete the matching scheduled reminder and store the item in the task or memory layer.
Use get_weather_forecast when the user asks about weather, rain, temperature, umbrella guidance, or when a scheduled reminder prompt asks for weather.
Use web_search and web_extract for current public web information, and include source URLs when answering from web results.
For Google Calendar writes, create a reviewable calendar draft first unless the request is an explicit approval of an existing draft.
Keep Slack replies concise and actionable.`;

const region = process.env.BEDROCK_REGION ?? process.env.AWS_REGION ?? process.env.AWS_DEFAULT_REGION ?? "ap-northeast-1";
const modelId = requireEnv("BEDROCK_MODEL_ID");
const documentModelId = process.env.BEDROCK_DOCUMENT_MODEL_ID ?? modelId;
const bedrockServiceTier = parseBedrockServiceTier(process.env.BEDROCK_SERVICE_TIER);
const secretsProvider = new SecretsProvider();

async function main(): Promise<void> {
  const [{ BedrockAgentCoreApp }, { createAmazonBedrock }, { defaultProvider }, ai] = await Promise.all([
    dynamicImport<{ BedrockAgentCoreApp: new (options: unknown) => { run: () => void } }>(
      "bedrock-agentcore/runtime",
    ),
    dynamicImport<{ createAmazonBedrock: (options: unknown) => (modelId: string) => unknown }>(
      "@ai-sdk/amazon-bedrock",
    ),
    dynamicImport<{ defaultProvider: () => unknown }>("@aws-sdk/credential-provider-node"),
    dynamicImport<{
      ToolLoopAgent: new (options: unknown) => { stream: (options: unknown) => Promise<{ fullStream: AsyncIterable<Record<string, unknown>> }> };
      jsonSchema: (schema: unknown) => unknown;
      tool: (options: unknown) => unknown;
    }>("ai"),
  ]);

  const bedrock = createAmazonBedrock({
    region,
    credentialProvider: defaultProvider(),
  });
  const app = new BedrockAgentCoreApp({
    invocationHandler: {
      requestSchema: agentRuntimeRequestSchema,
      process: async function* (request: AgentRuntimeRequest, context: { sessionId?: string }) {
        const log = logger.child({
          component: "agentcore-runtime",
          runtimeSessionId: context.sessionId,
          source: request.context.source,
        });
        const skillRegistry =
          request.disableTools || !request.toolContext ? null : createSkillRegistry(request);
        const executor = request.disableTools ? null : createToolExecutor(request, log, skillRegistry ?? undefined);
        const tools = executor ? createTools(ai, executor) : {};
        const skillPrompt =
          executor && skillRegistry
            ? await buildEnabledSkillPrompt(skillRegistry, request.toolContext!.workspaceId, log)
            : "";
        const selectedModelId = selectModelId(request);
        const agent = new ai.ToolLoopAgent({
          model: bedrock(selectedModelId),
          instructions: buildSystemPrompt(skillPrompt),
          tools,
          ...(bedrockServiceTier
            ? {
                providerOptions: {
                  bedrock: {
                    serviceTier: bedrockServiceTier,
                  },
                },
              }
            : {}),
        });

        log.info("AgentCore request started", {
          modelId: selectedModelId,
          bedrockRegion: region,
          bedrockServiceTier: bedrockServiceTier ?? "default",
          hasTools: Object.keys(tools).length > 0,
        });

        const history = getSessionHistory(context.sessionId, request);
        const userHistoryText = toHistoryText(request.content);
        const stream = await agent.stream({
          messages: [
            ...history,
            {
              role: "user",
              content: toUserContent(request.content),
            },
          ],
        });

        let assistantText = "";
        for await (const part of stream.fullStream) {
          if (part.type === "error") {
            throw new Error(`Model stream failed: ${formatStreamError(part.error)}`);
          }
          if (part.type !== "text-delta" || typeof part.text !== "string") {
            continue;
          }

          assistantText += part.text;
          yield { event: "message", data: { text: part.text } };
        }

        const summary = executor?.getSummary() ?? {
          taskIds: [],
          recurringTaskIds: [],
          savedMemoryIds: [],
          calendarDraftIds: [],
        };
        saveSessionHistory(context.sessionId, request, userHistoryText, assistantText);
        yield { event: "metadata", data: summary };
        log.info("AgentCore request completed", {
          taskIds: summary.taskIds,
          recurringTaskIds: summary.recurringTaskIds,
          savedMemoryIds: summary.savedMemoryIds,
          calendarDraftIds: summary.calendarDraftIds,
        });
      },
    },
  });

  app.run();
}

function createToolExecutor(
  request: AgentRuntimeRequest,
  log: ReturnType<typeof logger.child>,
  skillRegistry?: SkillRegistry,
): CustomToolExecutor | null {
  if (!request.resources || !request.toolContext) {
    return null;
  }

  const resources = request.resources;
  return new CustomToolExecutor(
    {
      memoryItems: new MemoryItemRepository(resources.memoryItemsTableName),
      channelMemories: new ChannelMemoryRepository(resources.memoryItemsTableName),
      userPreferences: new UserPreferenceRepository(resources.memoryItemsTableName),
      scheduledTasks: new TaskRepository(resources.scheduledTasksTableName),
      tasks: new TaskStateRepository(resources.tasksTableName),
      taskEvents: new TaskEventRepository(resources.taskEventsTableName),
      recurringTasks: new RecurringTaskRepository(resources.recurringTasksTableName),
      calendarDrafts: new CalendarDraftRepository(resources.calendarDraftsTableName),
    },
    {
      workspaceId: request.toolContext.workspaceId,
      userId: request.toolContext.userId,
      channelId: request.toolContext.channelId,
      conversationId: request.context.conversationTs,
      logger: log,
      memoryWritePolicy: request.toolContext.memoryWritePolicy,
    },
    {
      googleCalendarProvider: () =>
        createUserGoogleCalendarClient({
          workspaceId: request.toolContext!.workspaceId,
          userId: request.toolContext!.userId,
          defaultTimeZone: resources.googleCalendarTimeZone,
          googleCalendarSecretId: resources.googleCalendarSecretId,
          googleOAuthStartUrl: resources.googleOAuthStartUrl,
          secretsProvider,
          connections: new GoogleOAuthConnectionRepository(resources.googleOAuthConnectionsTableName),
        }),
      defaultCalendarTimeZone: resources.googleCalendarTimeZone,
      scheduledReminderScheduler:
        resources.schedulerTargetArn && resources.schedulerTargetRoleArn
          ? new EventBridgeScheduledReminderScheduler({
            scheduleGroupName: resources.schedulerScheduleGroupName ?? "default",
            scheduleNamePrefix: resources.schedulerScheduleNamePrefix ?? "serverless-agent",
            defaultTimeZone: resources.schedulerDefaultTimeZone ?? resources.googleCalendarTimeZone,
            targetArn: resources.schedulerTargetArn,
            targetRoleArn: resources.schedulerTargetRoleArn,
          })
          : undefined,
      weatherProvider: new OpenMeteoWeatherProvider(),
      webProvider: new WebToolsProvider({
        searchProvider: resources.webSearchProvider,
        searchApiKeyProvider: resources.webSearchApiKeyParameterName
          ? () => secretsProvider.getSecretString(resources.webSearchApiKeyParameterName!)
          : undefined,
        searchBaseUrl: resources.webSearchBaseUrl,
      }),
      skillRegistry,
    },
  );
}

function createSkillRegistry(request: AgentRuntimeRequest): SkillRegistry {
  const repository = request.resources?.skillsTableName
    ? new DynamoDbSkillRepository(request.resources.skillsTableName)
    : undefined;
  return new SkillRegistry(repository);
}

async function buildEnabledSkillPrompt(
  skillRegistry: SkillRegistry,
  workspaceId: string,
  log: ReturnType<typeof logger.child>,
): Promise<string> {
  try {
    return formatSkillSummariesForPrompt(await skillRegistry.listEnabledSummaries(workspaceId));
  } catch (error) {
    log.warn("Failed to load skill summaries", {
      error: error instanceof Error ? error.message : String(error),
    });
    return "";
  }
}

function buildSystemPrompt(skillPrompt: string): string {
  return [defaultSystemPrompt, skillPrompt].filter(Boolean).join("\n\n");
}

function getSessionHistory(
  sessionId: string | undefined,
  request: AgentRuntimeRequest,
): SessionHistoryMessage[] {
  if (!shouldUseSessionHistory(sessionId, request)) {
    return [];
  }

  return sessionHistories.get(sessionId!) ?? [];
}

function saveSessionHistory(
  sessionId: string | undefined,
  request: AgentRuntimeRequest,
  userText: string,
  assistantText: string,
): void {
  if (!shouldUseSessionHistory(sessionId, request)) {
    return;
  }

  const previous = sessionHistories.get(sessionId!) ?? [];
  const next = [
    ...previous,
    { role: "user" as const, content: userText },
    { role: "assistant" as const, content: assistantText },
  ].slice(-maxSessionHistoryMessages);
  sessionHistories.set(sessionId!, next);
}

function shouldUseSessionHistory(
  sessionId: string | undefined,
  request: AgentRuntimeRequest,
): boolean {
  return Boolean(sessionId && ["direct_chat_api", "scheduler"].includes(request.context.source));
}

function selectModelId(request: AgentRuntimeRequest): string {
  return hasModelBinaryInput(request.content) ? documentModelId : modelId;
}

function hasModelBinaryInput(blocks: AgentContentBlock[]): boolean {
  return blocks.some((block) => block.type === "image" || (block.type === "document" && block.source.type !== "text"));
}

function formatStreamError(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }
  if (typeof error === "string") {
    return error;
  }
  return JSON.stringify(error);
}

function createTools(
  ai: {
    jsonSchema: (schema: unknown) => unknown;
    tool: (options: unknown) => unknown;
  },
  executor: CustomToolExecutor,
): Record<string, unknown> {
  return Object.fromEntries(
    customToolDefinitions.map((definition) => [
      definition.name,
      ai.tool({
        description: definition.description,
        inputSchema: ai.jsonSchema(definition.input_schema),
        execute: async (input: Record<string, unknown>) => {
          const result = await executor.execute({
            id: `agentcore_tool_${Date.now()}_${definition.name}`,
            type: "agent.tool_use",
            name: definition.name,
            input,
          });
          return simplifyToolResult(result);
        },
      }),
    ]),
  );
}

function simplifyToolResult(result: ToolExecutionResult): Record<string, unknown> {
  return {
    isError: Boolean(result.isError),
    content: (result.content ?? []).map((block) => {
      if (block.type === "text") {
        return { type: "text", text: block.text };
      }
      return {
        type: block.type,
        note: "Non-text tool output was returned.",
      };
    }),
  };
}

function toHistoryText(blocks: AgentContentBlock[]): string {
  return blocks
    .map((block) => {
      if (block.type === "text") {
        return block.text;
      }

      if (block.type === "image") {
        return block.source.type === "url"
          ? `[Image attachment: ${block.source.url}]`
          : `[Image attachment: ${block.source.media_type}]`;
      }

      const title = block.title ?? "untitled";
      if (block.source.type === "text") {
        return [
          `Attached document: ${title}`,
          block.context,
          truncateForHistory(block.source.data),
        ]
          .filter(Boolean)
          .join("\n\n");
      }
      if (block.source.type === "url") {
        return `Attached document: ${title} (${block.source.url})`;
      }
      if (block.source.type === "base64") {
        return `Attached document: ${title} (${block.source.media_type})`;
      }
      return `Attached document: ${title} (${block.source.file_id})`;
    })
    .join("\n\n")
    .trim();
}

function truncateForHistory(value: string): string {
  const maxLength = 4000;
  return value.length <= maxLength ? value : `${value.slice(0, maxLength)}\n[truncated]`;
}

function toUserContent(blocks: AgentContentBlock[]): Array<Record<string, unknown>> {
  const content: Array<Record<string, unknown>> = [];

  for (const block of blocks) {
    if (block.type === "text") {
      content.push({ type: "text", text: block.text });
      continue;
    }

    if (block.type === "image") {
      if (block.source.type === "url") {
        content.push({ type: "image", image: new URL(block.source.url) });
        continue;
      }
      content.push({
        type: "image",
        image: block.source.data,
        mediaType: block.source.media_type,
      });
      continue;
    }

    if (block.source.type === "text") {
      content.push({
        type: "text",
        text: [
          `Attached document: ${block.title ?? "untitled"}`,
          block.context,
          block.source.data,
        ]
          .filter(Boolean)
          .join("\n\n"),
      });
      continue;
    }

    if (block.source.type === "base64") {
      content.push({
        type: "file",
        data: block.source.data,
        filename: block.title,
        mediaType: block.source.media_type,
      });
      continue;
    }

    if (block.source.type === "url") {
      content.push({
        type: "file",
        data: new URL(block.source.url),
        filename: block.title,
        mediaType: block.source.media_type ?? inferMediaTypeFromTitle(block.title),
      });
      continue;
    }

    content.push({
      type: "text",
      text: `Attachment note: ${block.title ?? block.source.file_id} could not be sent to the model.`,
    });
  }

  return content;
}

function inferMediaTypeFromTitle(title: string | undefined): string {
  const lower = title?.toLowerCase() ?? "";
  if (lower.endsWith(".pdf")) {
    return "application/pdf";
  }
  if (lower.endsWith(".md") || lower.endsWith(".markdown")) {
    return "text/markdown";
  }
  if (lower.endsWith(".txt")) {
    return "text/plain";
  }
  if (lower.endsWith(".csv")) {
    return "text/csv";
  }
  if (lower.endsWith(".docx")) {
    return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
  }
  if (lower.endsWith(".doc")) {
    return "application/msword";
  }
  if (lower.endsWith(".xlsx")) {
    return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
  }
  if (lower.endsWith(".xls")) {
    return "application/vnd.ms-excel";
  }
  if (lower.endsWith(".html") || lower.endsWith(".htm")) {
    return "text/html";
  }
  return "application/octet-stream";
}

function requireEnv(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) {
    throw new Error(`${name} must be set`);
  }
  return value;
}

function parseBedrockServiceTier(value: string | undefined): BedrockServiceTier | undefined {
  if (!value) {
    return undefined;
  }
  if (bedrockServiceTiers.includes(value as BedrockServiceTier)) {
    return value as BedrockServiceTier;
  }
  throw new Error(`Invalid BEDROCK_SERVICE_TIER '${value}'. Expected one of: ${bedrockServiceTiers.join(", ")}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
