import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";

const manifestSchema = z.object({
  skillId: z.string().min(1),
  version: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(1),
  defaultEnabled: z.boolean(),
  triggerHints: z.array(z.string().min(1)).default([]),
  toolAllowlist: z.array(z.string().min(1)).default([]),
  constraints: z.record(z.string(), z.unknown()).default({}),
});

const root = process.cwd();
const skillsDir = join(root, "skills", "builtin");
const outputPath = join(root, "src", "skills", "builtinCatalog.generated.ts");

const definitions = readdirSync(skillsDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => {
    const skillDir = join(skillsDir, entry.name);
    const manifest = manifestSchema.parse(
      JSON.parse(readFileSync(join(skillDir, "manifest.json"), "utf8")),
    );
    const body = readFileSync(join(skillDir, "SKILL.md"), "utf8").trim();
    return {
      ...manifest,
      body,
    };
  })
  .sort((a, b) => a.skillId.localeCompare(b.skillId));

const source = [
  "import type { BuiltinSkillDefinition } from \"./types\";",
  "",
  "// Generated by scripts/generate-builtin-skills.ts. Do not edit manually.",
  `export const builtinSkillDefinitions = ${JSON.stringify(definitions, null, 2)} satisfies BuiltinSkillDefinition[];`,
  "",
].join("\n");

writeFileSync(outputPath, source);
